### ISSUE TITLE
Is there a faster way to download the data?

### ISSUE THREAD

**Issue by imjiangjun** [ondyari/FaceForensics#11]
I have downloaded some data using the script provided. It is very convenient but ... the speed is too slow (~100kB/s) and it may cost three or more weeks. Is there a faster way to download the data (e.g Google Drive)? Many thanks!

**Comment by bhrt-sharma** [comment]
did you get the answer?

**Comment by imjiangjun** [comment]
@bhrt-sharma No any reply util now.

**Comment by Shimingyi** [comment]
I got 3mb/s when I use the network in my university.

**Comment by shubham5000** [comment]
Bro can you explain how to run the script...??

**Comment by imjiangjun** [comment]
@shubham5000 See [https://github.com/ondyari/FaceForensics/blob/master/dataset/README.md](https://github.com/ondyari/FaceForensics/blob/master/dataset/README.md)

**Comment by Ginly** [comment]
> 我已经使用提供的脚本下载了一些数据。这非常方便，但是...速度太慢（〜100kB / s），可能要花三周或更长时间。有没有更快的下载数据的方法（例如Google云端硬盘）？非常感谢！

guys, have you downloaded it, you can share it?

**Comment by Ginly** [comment]
> I have downloaded some data using the script provided. It is very convenient but ... the speed is too slow (~100kB/s) and it may cost three or more weeks. Is there a faster way to download the data (e.g Google Drive)? Many thanks!

guys, have you downloaded it, you can share it?

**Comment by cbhxdyx** [comment]
> I have downloaded some data using the script provided. It is very convenient but ... the speed is too slow (~100kB/s) and it may cost three or more weeks. Is there a faster way to download the data (e.g Google Drive)? Many thanks!

我在用脚本下载时一直显示“系统找不到文件路径”，可是我的输出路径没有问题呀，求助需要“DeepFakeDetection_original”

**Comment by ZuoyanL** [comment]
Bro， have you downloaded it ? My server is located in China, so it's too slow to download it. Could you please share it ?

**Comment by imjiangjun** [comment]
@Ginly @ZuoyanL I haven't downloaded it. It was too slow so I gave up at that time. Maybe I will try it again in the future.

**Comment by LonelyPlanetIoT** [comment]
> @Ginly @ZuoyanL I haven't downloaded it. It was too slow so I gave up at that time. Maybe I will try it again in the future.

Have you downlodaed it successfully?
