### ISSUE TITLE
Problem with downloading the FaceForensics dataset

### ISSUE THREAD

**Issue by mrkoujan** [ondyari/FaceForensics#14]
Hello,

Thanks for your consent about sharing your dataset.

I was just trying to use the download script sent to me to download your dataset. However, when trying to do so, I get the following message: 
urllib.error.HTTPError: HTTP Error 404: Not Found

The problem is happening when downloading this file:
http://kaldir.vc.in.tum.de/FaceForensics/v3/manipulated_sequences/Face2Face/raw/videos/585_599.mp4

It seems to me that there might be a problem with hosting server.

Is the hosting server OK?

Many thanks,

**Comment by WYing333** [comment]
Hi, I encountered the similar problem, did you managed to solve it?
