### ISSUE TITLE
Can't access FaceForensics_TOS.pdf

### ISSUE THREAD

**Issue by taogelose** [ondyari/FaceForensics#2]
I tried to download the FaceForensics Terms of Use through the link "http://kaldir.vc.in.tum.de/FaceForensics/webpage/FaceForensics_TOS.pdf"

but got "Forbidden You don't have permission to access /FaceForensics/webpage/FaceForensics_TOS.pdf on this server."

BTW, I am wondering whether the code and model would be released for research.

Thanks.

**Comment by giorgiop** [comment]
Same issue here

**Comment by JeremiahJoe** [comment]
The same here :(

**Comment by ondyari** [comment]
Hi, sorry for the late reply. Our fileserver was down during that time which included the link to the TOS. We are switching to google forms to avoid this in the future.
