### ISSUE TITLE
url lib Timeout error when trying to download

### ISSUE THREAD

**Issue by t0nyj** [ondyari/FaceForensics#27]
> urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>

I am getting this error while trying to use the script to download. How to resolve this??

**Comment by Gun-mIn** [comment]
> > urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
> 
> I am getting this error while trying to use the script to download. How to resolve this??

How did you resolve this problem??
