### ISSUE TITLE
Provided weights are TransferModel and not OrderedDict, expected by return_pytorch04_xception()

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [ondyari/FaceForensics#8]
The weights linked in the classification directory are TransferModels and not OrderedDict which is expected by the return_pytorch04_xception() function. This prohibits one from loading these weights with the current code.

**Comment by haqkiemdaim** [comment]
@Baukebrenninkmeijer then how you find the OrderedDict weights ya ?
Because i got below error when running below:
```
 model = model.cuda()
AttributeError: 'collections.OrderedDict' object has no attribute 'cuda'
```

Hope you can help me with that

**Comment by Baukebrenninkmeijer** [comment]
I don't have the exact code right now, but you need to load it as a torch module instead of as a OrderedDict. Iirc, this error was caused by the downloading the 'wrong' weights. There are several available in the repo.

**Comment by haqkiemdaim** [comment]
@Baukebrenninkmeijer ouhh i see. 

So now the problem is on the model or is it on how the code load it ya?

Did you face the same problem like me before?

Sory to ask but which repo do u mean ya?

**Comment by Baukebrenninkmeijer** [comment]
We used faceforensics here: [https://github.com/Baukebrenninkmeijer/FakeFynder-Hackathon-for-Good-2019](https://github.com/Baukebrenninkmeijer/FakeFynder-Hackathon-for-Good-2019). Most of what we used from faceforensics was in the `classification` folder. 

The weights we used were linked in the classification readme of the faceforensics repo [http://kaldir.vc.in.tum.de/FaceForensics/models/faceforensics++_models.zip](http://kaldir.vc.in.tum.de/FaceForensics/models/faceforensics++_models.zip), which you probably found. If you load them with torch.load instead of the provided code, I think it works. 

If this still doesn't work, I will need to check myself tonight or tomorrow.

**Comment by sahla90** [comment]
I installed all that are provided in requirements.txt . Then When I am running in jupitor notebook as
run detect_from_video.py -i tst.mp4 -m classification/weights/face_detection/xception/all_raw.p --cuda
I am getting error
FileNotFoundError: [Errno 2] No such file or directory: '/home/ondyari/.torch/models/xception-b5690688.pth'
What I have to do to resolve those
pls help

**Comment by Edwardmark** [comment]
@Baukebrenninkmeijer which model is to use? .p file or .h5 file? Could you be more specific?
